name: Github API
run-name: Github Scripts

on:
  workflow_dispatch:

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v7
        env:
          SHA: "${{env.parentSHA}}"
        with:
          script: |
            const script = require('./scripts/github-script.js')
            await script({github, context, core})
